/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutLayout: typeof import('./src/layout/AboutLayout.vue')['default']
    Content: typeof import('./src/model/Content.vue')['default']
    FriendLayout: typeof import('./src/layout/FriendLayout.vue')['default']
    HomeLayout: typeof import('./src/layout/HomeLayout.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    NoDevice: typeof import('./src/pages/NoDevice.vue')['default']
    PhotoLayout: typeof import('./src/layout/PhotoLayout.vue')['default']
    ProjectLayout: typeof import('./src/layout/ProjectLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLayout: typeof import('./src/layout/WebsiteLayout.vue')['default']
    UserInfo: typeof import('./src/model/UserInfo.vue')['default']
    WebsiteLayout: typeof import('./src/layout/WebsiteLayout.vue')['default']
  }
}
